import {
	type EnkoreAutogeneratedFile,
	createEntity
} from "@anio-software/enkore-private.spec"
import type {AutogenerateAPIContext} from "#~src/autogenerate/AutogenerateAPIContext.ts"
import type {Options} from "./Options.ts"
import type {Variant} from "./Variant.ts"
import {destinationPathToFunctionName} from "./destinationPathToFunctionName.ts"
import {_generateFactoryCode} from "./_generateFactoryCode.ts"

export function _generateFactoryFile(
	apiContext: AutogenerateAPIContext,
	options: Options,
	variant: Variant
): EnkoreAutogeneratedFile {
	const exportName = destinationPathToFunctionName(
		options.destination
	).slice(0, -("Factory".length))

	return createEntity("EnkoreAutogeneratedFile", 0, 0, {
		destinationPath: options.destination,
		generator(session) {
			return _generateFactoryCode(
				apiContext,
				session,
				options,
				exportName,
				variant
			)
		}
	})
}
