import {
	type EnkoreAutogeneratedFile,
	createEntity
} from "@anio-software/enkore-private.spec"
import type {AutogenerateAPIContext} from "#~src/autogenerate/AutogenerateAPIContext.ts"
import type {Options} from "./Options.ts"
import {destinationPathToFunctionName} from "./destinationPathToFunctionName.ts"
import {_generateInstantiationCode} from "./_generateInstantiationCode.ts"
import path from "node:path"

export function _generateInstantiationFile(
	apiContext: AutogenerateAPIContext,
	options: Options
): EnkoreAutogeneratedFile {
	const exportName = destinationPathToFunctionName(
		options.destination
	).slice(0, -("Factory".length))

	const destinationPath = path.join(
		path.dirname(options.destination),
		`${exportName}.ts`
	)

	return createEntity("EnkoreAutogeneratedFile", 0, 0, {
		generateAfterPreprocessing: true,
		destinationPath,
		generator() {
			return _generateInstantiationCode(
				apiContext,
				exportName,
				options.__forceCompatibility === true
			)
		}
	})
}
