import {
	type EnkoreAutogeneratedFile,
	createEntity
} from "@anio-software/enkore-private.spec"
import type {AutogenerateAPIContext} from "#~src/autogenerate/AutogenerateAPIContext.ts"
import type {Options} from "./Options.ts"
import type {Variant} from "./Variant.ts"
import {_generateTryFactoryCode} from "./_generateTryFactoryCode.ts"
import {destinationPathToFunctionName} from "./destinationPathToFunctionName.ts"

export function _generateTryFactoryFile(
	context: AutogenerateAPIContext,
	options: Options,
	variant: Variant
): EnkoreAutogeneratedFile {
	const exportName = destinationPathToFunctionName(
		options.destination
	).slice(0, -("Factory".length))

	return createEntity("EnkoreAutogeneratedFile", 0, 0, {
		generateAfterPreprocessing: true,
		destinationPath: "project/src/AAAAA.ts",
		generator(session) {
			return _generateTryFactoryCode(
				context,
				session,
				options,
				exportName,
				variant
			)
		}
	})
}
