import type {AutogenerateAPIContext} from "#~src/autogenerate/AutogenerateAPIContext.mts"
import type {EnkoreAutogeneratedFile} from "@anio-software/enkore-private.spec"
import type {Options} from "./Options.mts"
import type {Generator} from "./Generator.mts"
import {
	isAsyncSyncExpandableFilePath,
	expandAsyncSyncVariantFilePath
} from "@enkore/target-js-utils"

export function expand(
	apiContext: AutogenerateAPIContext,
	options: Options,
	generator: Generator
): EnkoreAutogeneratedFile[] {
	const {source, destination} = options

	if (!isAsyncSyncExpandableFilePath(source)) {
		throw new Error(`source must be expandable.`)
	} 
	else if (!isAsyncSyncExpandableFilePath(destination)) {
		throw new Error(`destination must be expandable.`)
	}

	const expandedSource = expandAsyncSyncVariantFilePath(source)
	const expandedDestination = expandAsyncSyncVariantFilePath(destination)

	return [
		...generator.call(apiContext, {
			source: expandedSource[0],
			destination: expandedDestination[0]
		}, "asyncVariant"),
		...generator.call(apiContext, {
			source: expandedSource[1],
			destination: expandedDestination[1]
		}, "syncVariant")
	]
}
