import type {AutogenerateAPIContext} from "#~src/autogenerate/AutogenerateAPIContext.ts"
import type {EnkoreAutogeneratedFile} from "@anio-software/enkore-private.spec"
import type {Options} from "./Options.ts"
import type {Variant} from "./Variant.ts"

export type Generator = (
	this: AutogenerateAPIContext,
	options: Options,
	// this is to be able to tell if expand() was used
	// users should never set this value
	__internalIsAsyncSyncVariant?: Variant
) => EnkoreAutogeneratedFile[]
