import type {AutogenerateAPIContext} from "#~src/autogenerate/AutogenerateAPIContext.mts"
import type {EnkoreAutogeneratedFile} from "@asint/enkore__spec"
import type {Options} from "./Options.mts"
import type {Variant} from "./Variant.mts"

export type Generator = (
	this: AutogenerateAPIContext,
	options: Options,
	// this is to be able to tell if expand() was used
	// users should never set this value
	__internalIsAsyncSyncVariant?: Variant
) => EnkoreAutogeneratedFile[]
